server:
  port: 8686

# database setting
spring:

  #mail setting
  mail:
    host: smtp.naver.com
    port: 465
    username: pos03167
    password: dldPwls0619.
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
    default-encoding: UTF-8
    debug: true



  datasource:
    url: jdbc:mariadb://localhost:3306/jpastudy
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    # DBMS dialect setting
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      # ddl ??? ??? ????..none ?? update create
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # SQL ?? ??? ??? ??
    database: mysql

# log level setting
logging:
  level:
    root: info
    com:
      spring:
        jpastudy: debug
    org:
      hibernate:
        SQL: debug


study:
  mail:
    host: pos03167@naver.com



